# -*- coding: utf-8 -*-
"""Mutual Funds Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CKsxa3bwqJXBBOynLuKljyaP8_mhDnAG
"""

# Step 1: Install Required Libraries
# These libraries are usually pre-installed in Google Colab, but it's good to ensure they're available.
!pip install pandas matplotlib seaborn

# Step 2: Upload the CSV File
from google.colab import files
uploaded = files.upload()  # This will prompt you to upload your CSV file.

# Step 3: Load the CSV File
import pandas as pd

# Replace 'your_file.csv' with the name of your uploaded file
file_name = list(uploaded.keys())[0]
data = pd.read_csv("Mutual Funds Analysis.csv")

# Preview the data
print("Data Preview:")
print(data.head())

import matplotlib.pyplot as plt
import pandas as pd

# Sample data
data = {
    "Date": ["2023-12-01", "2023-12-02", "2023-12-03", "2023-12-04", "2023-12-05"],
    "RELIANCE.NS": [2950.00, 2955.00, 2960.00, 2965.00, 2970.00]
}

df = pd.DataFrame(data)

# Convert Date column to datetime
df["Date"] = pd.to_datetime(df["Date"])

# Plotting the line chart
plt.figure(figsize=(10, 5))
plt.plot(df["Date"], df["RELIANCE.NS"], marker='o', color='b', label="RELIANCE.NS")
plt.title("RELIANCE Stock Price Over Time")
plt.xlabel("Date")
plt.ylabel("Stock Price (INR)")
plt.xticks(rotation=45)
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

# Sample data
data = {
    "Stock": ["RELIANCE.NS", "HDFCBANK.NS", "ICICIBANK.NS"],
    "Price": [2950.00, 1655.00, 1200.00]
}

df = pd.DataFrame(data)

# Bar plot without hue, no legend needed
plt.figure(figsize=(8, 5))
sns.barplot(x="Stock", y="Price", data=df)
plt.title("Comparison of Stock Prices")
plt.xlabel("Stock")
plt.ylabel("Price (INR)")
plt.show()

import matplotlib.pyplot as plt

# Last day's prices
last_day = df.iloc[-1]

# Pie chart for stock prices on the last day
plt.figure(figsize=(10, 8))
plt.pie(last_day, labels=last_day.index, autopct='%1.1f%%', startangle=140, colors=plt.cm.Paired.colors)
plt.title("Stock Price Distribution on 5th Day")
plt.axis('equal')  # Equal aspect ratio ensures that pie chart is drawn as a circle.
plt.show()

import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt

# Sample data (price data for multiple stocks)
data = {
    "RELIANCE.NS": [2950.00, 2955.00, 2960.00, 2965.00, 2970.00],
    "HDFCBANK.NS": [1655.00, 1660.00, 1665.00, 1670.00, 1675.00],
    "ICICIBANK.NS": [1200.00, 1205.00, 1210.00, 1215.00, 1220.00],
    "INFY.NS": [1900.00, 1905.00, 1910.00, 1915.00, 1920.00],
    "TCS.NS": [3100.00, 3105.00, 3110.00, 3115.00, 3120.00],
    "KOTAKBANK.NS": [1805.00, 1810.00, 1815.00, 1820.00, 1825.00],
    "HINDUNILVR.NS": [2751.05, 2755.00, 2760.00, 2765.00, 2770.00],
    "ITC.NS": [498.80, 500.00, 502.00, 505.00, 507.00],
    "LT.NS": [3572.70, 3580.00, 3590.00, 3600.00, 3610.00],
    "HEROMOTOCO.NS": [5244.40, 5250.00, 5260.00, 5270.00, 5280.00],
    "DRREDDY.NS": [6965.35, 6980.00, 7000.00, 7020.00, 7050.00],
    "SHREECEM.NS": [24730.55, 24750.00, 24780.00, 24800.00, 24830.00],
    "BRITANNIA.NS": [5765.80, 5780.00, 5800.00, 5820.00, 5840.00],
    "UPL.NS": [566.15, 567.00, 568.00, 569.00, 570.00],
    "EICHERMOT.NS": [4883.25, 4900.00, 4920.00, 4950.00, 4970.00],
    "SBILIFE.NS": [1761.30, 1770.00, 1780.00, 1790.00, 1800.00],
    "ADANIPORTS.NS": [1492.55, 1495.00, 1500.00, 1505.00, 1510.00],
    "BAJAJ-AUTO.NS": [9779.70, 9800.00, 9820.00, 9840.00, 9860.00],
    "HINDALCO.NS": [672.90, 675.00, 680.00, 685.00, 690.00]
}

# Convert data to DataFrame
df = pd.DataFrame(data)

# Correlation matrix
corr = df.corr()

# Heatmap visualization
plt.figure(figsize=(12, 10))
sns.set(style="white")  # Optional, sets the background style
sns.heatmap(corr, annot=True, cmap="coolwarm", fmt=".2f", linewidths=0.5, cbar_kws={'label': 'Correlation Coefficient'})

# Title and layout adjustments
plt.title("Correlation Matrix of Stock Prices")
plt.tight_layout()  # Makes sure everything fits properly
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

# Plotting the stock prices over time (5 days)
plt.figure(figsize=(12, 6))
sns.lineplot(data=df, palette="tab10", linewidth=2)
plt.title("Stock Prices Over Time (5 Days)")
plt.xlabel("Days")
plt.ylabel("Stock Price")
plt.legend(title="Stocks", bbox_to_anchor=(1.05, 1), loc="upper left")
plt.tight_layout()
plt.show()

# Bar plot for stock prices on the last day (5th day)
last_day = df.iloc[-1]

plt.figure(figsize=(12, 6))
sns.barplot(x=last_day.index, y=last_day.values, color=sns.color_palette("Blues_d")[0])
plt.title("Stock Prices on 5th Day")
plt.xlabel("Stocks")
plt.ylabel("Stock Price")
plt.xticks(rotation=90)  # Rotate x-axis labels by 90 degrees (vertical)
plt.tight_layout()
plt.show()